import AWO_EM_MODULE from "../../assets/AWO.js";
import { LoadingService} from "../loading/loading.service";

/**
 * Initialization functions for the game.
 */

/**
 * Loads the AWO game. Updates the loading shared service's state as the game loads.
 * @param gameCanvas Reference to the canvas element used by the game.
 * @param loadingService Reference to the app's loading service
 * @param emDirPath Path to directory containing files generated by emscripten.
 * @param runtimeInitializedCb Function called when the game's runtime is initialized.
 * @returns The module object used by emscripten.
 */
export function loadGame(
    gameCanvas: HTMLCanvasElement,
    loadingService: LoadingService,
    emDirPath: string,
    runtimeInitializedCb: () => void,
): any {

    // Add adjustments to the canvas element.
    // TODO: make more user-friendly
    gameCanvas.addEventListener("webglcontextlost", (e) => {
        alert("WebGL context lost. You will need to reload the page.");
        e.preventDefault();
    }, false);

    loadingService.start("Loading...");

    // Object with custom properties for AWO emscripten module to use
    return AWO_EM_MODULE({
        preRun:  [],
        postRun: [],

        // Prints `printf` outputs.
        print(text: string) {
            if (arguments.length > 1) {
                text = Array.prototype.slice.call(arguments).join(" ");
            }

            console.log(text);
        },

        // Prints error messages
        printErr(text: string) {
            if (arguments.length > 1) {
                text = Array.prototype.slice.call(arguments).join(" ");
            }

            console.error(text);
        },

        // Used by module to get the canvas element
        canvas: (() => {
            return gameCanvas;
        })(),

        // Set the current loading status message
        setStatus(text: string) {
            if (!this.setStatus.last) {
                this.setStatus.last = { time: Date.now(), text: "" };
            }

            if (text === this.setStatus.last.text) {
                return;
            }

            const m = text.match(/([^(]+)\((\d+(\.\d+)?)\/(\d+)\)/);
            const now = Date.now();

            if (m && now - this.setStatus.last.time < 30) {
                // return; // If this is a progress update, skip it if too soon
            }

            this.setStatus.last.time = now;
            this.setStatus.last.text = text;

            // Update loading text
            loadingService.update(undefined, text);
        },

        totalDependencies: 0,

        // Current/max amount of times `monitorRunDependencies` gets called.
        currentRDCalls: 0,
        maxRDCalls: 14,

        monitorRunDependencies(remaining: number) {

            // Update loading progress
            loadingService.update(
                ((++this.currentRDCalls) / this.maxRDCalls) * 100
            );

            this.totalDependencies = Math.max(this.totalDependencies, remaining);

            this.setStatus(
                remaining
                    ? "Preparing... (" + (this.totalDependencies - remaining) + "/" + this.totalDependencies + ")"
                    : "All downloads complete.",
            );
        },

        // Adjust location of files queried for
        locateFile(path: string, prefix: string) {
            return emDirPath + path;
        },

        // TODO: Set behaviour when abnormal program termination occurs
        onAbort() {
        },

        onRuntimeInitialized() {
            loadingService.end();
            runtimeInitializedCb();
        },
    });
}

/**
 * Initialize the loaded game.
 * @param emModuleObj The emscripten module object.
 * @returns Pointer to the game instance.
 */
export function initGame(emModuleObj: any): number {
    let gamePtr: number; // Pointer to the game instance

    // Get width/height of user's window to pass to game
    const width: number  = window.innerWidth || document.documentElement.clientWidth || document.body.clientWidth;
    const height: number = window.innerHeight|| document.documentElement.clientHeight|| document.body.clientHeight;

    // Initialize and start running game
    // TODO: Height should compensate for additional UI at bottom of screen
    gamePtr = emModuleObj.ccall("init_AWO", "number", ["number", "number"], [width, height]);
    emModuleObj.ccall("run_AWO", null, ["number"], [gamePtr]);

    return gamePtr;
}
